Add the randstran function

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -77,6 +77,24 @@ function b64dump () {
 }
 
 ##
+## randstran - Generate a random alphanumeric string (lowercase)
+##
+function randstran () {
+    local anchars=({0..9} {a..z})
+    local len=${1:-8}
+    if ! [[ ${len} =~ '^[0-9]+$' ]]; then
+        echo 'Error: Invalid string length' >&2; return 1
+    fi
+    if [[ ${len} < 1 ]]; then
+        echo 'Error: Length must be 1 or larger' >&2; return 1
+    fi
+    for i in {1..${len}}; do
+        echo -n $anchars[$((${RANDOM} % 36 + 1))]
+    done
+    echo
+}
+
+##
 ## Detect active tmux sessions
 ##
 if type tmux > /dev/null; then
