Add randstranu()

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -113,6 +113,24 @@ function randstranl () {
 }
 
 ##
+## randstranu - Generate a random alphanumeric string (all uppercase)
+##
+function randstranu () {
+    local anchars=({0..9} {A..Z})
+    local len=${1:-8}
+    if ! [[ ${len} =~ '^[0-9]+$' ]]; then
+        echo 'Error: Invalid string length' >&2; return 1
+    fi
+    if [[ ${len} < 1 ]]; then
+        echo 'Error: Length must be 1 or larger' >&2; return 1
+    fi
+    for i in {1..${len}}; do
+        echo -n $anchars[$((${RANDOM} % 36 + 1))]
+    done
+    echo
+}
+
+##
 ## randstr - Generate a random string
 ##
 function randstr () {
